# Generated by Django 5.0.14 on 2026-06-23 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=500)),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('sentimiento', models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo'), ('neutral', 'Neutral'), ('unknown', 'Desconocido')], default='unknown', max_length=10)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='OHLCVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
            ],
            options={
                'verbose_name': 'Vela OHLCV',
                'verbose_name_plural': 'Velas OHLCV',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(help_text='Símbolo del activo, ej. BTC, ETH, SOL', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('timeframe', models.CharField(default='1d', help_text='Marco temporal de las velas, ej. 1h, 4h, 1d', max_length=10)),
            ],
            options={
                'verbose_name': 'Dataset de precios',
                'verbose_name_plural': 'Datasets de precios',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='PatternDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_patron', models.CharField(choices=[('hammer', 'Hammer (martillo)'), ('inverted_hammer', 'Inverted hammer'), ('doji', 'Doji'), ('bullish_engulfing', 'Bullish engulfing'), ('bearish_engulfing', 'Bearish engulfing'), ('morning_star', 'Morning star'), ('evening_star', 'Evening star')], max_length=30)),
                ('confianza', models.FloatField(default=1.0, help_text='Valor entre 0 y 1 indicando qué tan bien calza la vela con la definición del patrón')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('vela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_detectados', to='crypto_analyzer.ohlcvrecord')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones', to='crypto_analyzer.pricedataset')),
            ],
            options={
                'verbose_name': 'Patrón detectado',
                'verbose_name_plural': 'Patrones detectados',
                'ordering': ['vela__timestamp'],
            },
        ),
        migrations.AddField(
            model_name='ohlcvrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velas', to='crypto_analyzer.pricedataset'),
        ),
        migrations.AddIndex(
            model_name='ohlcvrecord',
            index=models.Index(fields=['dataset', 'timestamp'], name='crypto_anal_dataset_5e34b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvrecord',
            unique_together={('dataset', 'timestamp')},
        ),
    ]
